services:
  questdb:
    image: questdb/questdb
    ports:
      - 9000:9000
      - 9009:9009
    networks:
      - internal
    volumes:
      - questdb_data:/var/lib/questdb
  
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    networks:
      - internal
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  internal:

volumes:
  questdb_data:
  grafana_data: